### ISSUE TITLE
Functionally issues

### ISSUE THREAD

**Issue by tsrob50** [Maaaarden/VSCode-AzureAutomationExtension#35] opened 2019-02-09 21:52 UTC
I can connect, my runbooks show under Automation Explorer v 0.9.7
Clicking on a runbook will not download copy, no errors.
Creating a new runbook asks for name and runbook type, then does nothing.  No errors.
Other than view the existing runbooks, none of the functionality seems to work.

**Comment by Maaaarden** [comment] 2019-02-20 08:58
Hi @tsrob50 

Thanks for reporting this - it is now fixed in v1.0.0

It seems like a dependency to FS module in node.js, broke the extension. Had to add callback functionality to some code that wasn't working.
You should now be able to open and create runbooks.

**Comment by tsrob50** [comment] 2019-02-20 12:34
Thanks @Maaaarden 
I was able to confirm downloading, updating and running runbooks work.  I can't seem to create a new runbook through the plugin however from the "+" sign or command propt.

Thanks

**Comment by Maaaarden** [comment] 2019-02-20 13:10
@tsrob50 

This should be pushed out as a minor patch any minute now. Sorry for the inconvenience

**Comment by tsrob50** [comment] 2019-02-20 14:32
Great, Thanks for your help @Maaaarden!

**Comment by tsrob50** [comment] 2019-02-21 11:16
Hello @Maaaarden 
I now get "An error occurred while trying to create the runbook in Azure Cloud" when trying to create or publish a new runbook.  The runbook is created locally, but not in AA.  I verified that I can download and save an existing runbook to rule out a permission issue.

**Comment by Maaaarden** [comment] 2019-02-21 19:11
@tsrob50 

Thats odd - can't reproduce that issue. Just created new, edited, published and run it, with success.
I'm trying to put in some extra error handling. 
But, for now, could you try and bring forth the developer tools 'Ctrl + Shift + i), and select 'Console' - just post a whole log after you open it, and try to create new runbook, here. Thanks

**Comment by tsrob50** [comment] 2019-02-22 01:46
I uploaded the file to a private repo and added you as a contribute.  You should be able to get to it, if not let me know.  I did verify that the subscription and automation account name are correct.

Thanks

**Comment by Maaaarden** [comment] 2019-02-22 09:08
Hi @tsrob50 

Sounds really weird. According to the error message, either your subscriptionID or Automation Account name is wrong. But, if you've already checked it?

And, you get the list of runbooks in the menu on the left, right?

**Comment by tsrob50** [comment] 2019-02-22 11:48
I can get a list of runbooks and edit and publish existing ones.  I uploaded a log from publishing and saving a draft.

**Comment by Maaaarden** [comment] 2019-02-28 20:01
Hi @tsrob50 

Sorry for long delay - i've been looking into this, and can't seem to find heads or tails in this error you get.

Can you please give me a few pointers as to how i can try and reproduce?

**Comment by justinmetz** [comment] 2019-03-29 01:56
I am seeing this same error when trying to create runbooks via the addin.  What type of pointers are you looking for?  I will provide whatever I can to help out..

**Comment by justinmetz** [comment] 2019-03-29 02:04
This is the error I get in the activity log when I try to save a draft of a runbook that does not already exist in my Azure Automation account.  I used the "+" icon to create the runbook locally then attempted to save the draft..

Operation name
Write Draft
Time stamp
Thu Mar 28 2019 21:34:42 GMT-0400 (Eastern Daylight Time)
Event initiated by
AzureAutomationDeployer-Dev
Error code
ResourceNotFound
Message
The Resource 'Microsoft.Automation/automationAccounts/Jmetz-Auto01/runbooks/SomeRUnbook' under resource group 'Jmetz-Auto01' was not found.

**Comment by justinmetz** [comment] 2019-03-29 02:07
This is the error I get in the activity log when I try to save a draft of a runbook that does not already exist in my Azure Automation account. I used the "+" icon to create the runbook locally then attempted to save the draft..

Operation name
Write Draft
Time stamp
Thu Mar 28 2019 21:34:42 GMT-0400 (Eastern Daylight Time)
Event initiated by
AutomationApplication-Dev
Error code
ResourceNotFound
Message
The Resource 'Microsoft.Automation/automationAccounts/Jmetz-Acct01/runbooks/SomeRunbook' under resource group 'Jmetz-Acct01' was not found

**Comment by Maaaarden** [comment] 2019-04-03 12:43
Hi @justinmetz 

I will have a look into this based on your last entry. Sounds like there is something with the order of actions.

**Comment by Maaaarden** [comment] 2019-04-03 20:01
Hi @justinmetz and @tsrob50 

I might have found how you reached a point where this error occured. If you create the local file without using either the commandpalette or the + icon on the Automation view, it would not create the runbook in azure, since it didn't know what runbook type it was.

I've published a new version with a fix to this.

**Comment by Maaaarden** [comment] 2019-04-03 20:10
Hmm, reading the thread again - both of you write that you've been using the '+' icon, inside the extension view. However, this SHOULD have triggered the runbook to be created in Azure behind the scenes, while creating the local copy for you to watch.

Please let me know if the new release fixes your issue, or if it persists.

**Comment by tsrob50** [comment] 2019-04-19 11:57
Sorry for the delay.  I tried it again on two computers to the same AA account.  "Azure Automation: Create new Runbook" creates the runbook locally.  "Azure Automation: Save Draft" seems to run with no error, but does not save the runbook.  

Modifying, saving and running existing runbooks work without issue.

Activity Logs on the Automation Account shows the following error:
Operation name
Create or Update an Azure Automation Runbook
Time stamp
Fri Apr 19 2019 06:50:09 GMT-0500 (Central Daylight Time)
Event initiated by
VSCode
Error code
NotFound
Message
{"Message":"Could not find the account. SubscriptionId: xxxx-xxxx-xxxx-xxxx-xxxxxxx AccountName: CiraltosAutomation"}

**Comment by Maaaarden** [comment] 2021-11-05 22:06
Hi @tsrob50 and @gastori 

Sorry for the lack of response on this matter. 
I've just installed this freshly, with no error on creating runbooks. Please ensure the configuration properties are set correctly and try this again.

Regards

**Closed by Maaaarden** 2021-11-05 22:06 UTC
